"""initial migration

Revision ID: e62529cb846f
Revises: 
Create Date: 2024-01-10 01:51:28.512098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'e62529cb846f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), primary_key=True, index=True),
                    sa.Column('email', sa.String(), unique=True),
                    sa.Column('username', sa.String(), unique=True),
                    sa.Column('first_name', sa.String()),
                    sa.Column('last_name', sa.String()),
                    sa.Column('hashed_password', sa.String()),
                    sa.Column('is_active', sa.Boolean(), default=True),
                    sa.Column('role', sa.String()),
                    )

    op.create_table('stores',
                    sa.Column('store_id', sa.Integer(), primary_key=True, index=True, autoincrement=True),
                    sa.Column('store_name', sa.String(), index=True),
                    sa.Column('location', sa.String()),
                    sa.Column('address', sa.String(), default=None)
                    )

    op.create_table('products',
                    sa.Column('product_id', sa.Integer(), primary_key=True, index=True, autoincrement=True),
                    sa.Column('product_name', sa.String(), index=True),
                    sa.Column('is_available', sa.Boolean(), default=True),
                    sa.Column('store_id', sa.Integer()),
                    sa.ForeignKey('products_store_id_fkey', 'products', 'stores', ['store_id'], ['store_id']))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users'),
    op.drop_table('stores'),
    op.drop_table('products'),
    # ### end Alembic commands ###
